
CREATE TABLE TEAMZ(
    TEAM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_NAME VARCHAR2(20)    
);
CREATE TABLE TEAMW(
    MEM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_ID VARCHAR2(20),
    MEM_NAME VARCHAR2(20),
    MEM_AGE DECIMAL,
    ROLL VARCHAR2(20)
);

ALTER TABLE TEAMW ADD (ROLL VARCHAR2(20)) ;

ALTER TABLE TEAMW ADD CONSTRAINT TEAMW_fk_TEAM_ID
      FOREIGN KEY (TEAM_ID) REFERENCES TEAMZ(TEAM_ID);
      
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'A','저스티스');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'H','엘카로');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'C','가오갤');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'S','어벤저스');

INSERT INTO TEAMW VALUES ('01','A','형준','34');
INSERT INTO TEAMW VALUES ('02','A','세인','35');
INSERT INTO TEAMW VALUES ('03','A','희태','21');
INSERT INTO TEAMW VALUES ('04','A','상훈','29');
INSERT INTO TEAMW VALUES ('05','A','태형','25');
INSERT INTO TEAMW VALUES ('06','H','혜리','26');
INSERT INTO TEAMW VALUES ('07','H','지은','26');
INSERT INTO TEAMW VALUES ('08','H','준','27');
INSERT INTO TEAMW VALUES ('09','H','재경','30');
INSERT INTO TEAMW VALUES ('10','H','단아','26');
INSERT INTO TEAMW VALUES ('11','C','최정훈','32');
INSERT INTO TEAMW VALUES ('12','C','윤호','31');
INSERT INTO TEAMW VALUES ('13','C','가은','29');
INSERT INTO TEAMW VALUES ('14','C','정훈','23');
INSERT INTO TEAMW VALUES ('15','C','승태','30');
INSERT INTO TEAMW VALUES ('16','S','승호','27');
INSERT INTO TEAMW VALUES ('17','S','소진','26');
INSERT INTO TEAMW VALUES ('18','S','이슬','29');
INSERT INTO TEAMW VALUES ('19','S','진태','26');
INSERT INTO TEAMW VALUES ('20','S','누리','30');
